# Generated by Django 3.2.5 on 2022-02-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0002_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
