# Generated by Django 3.2.5 on 2022-02-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0003_rename_blogs_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='images/')),
                ('desc', models.TextField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='landseatechapp.blog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
